version: '3.1'
services:
  task-manager:
    image: 'node:14'
    user: 'node'
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    expose:
      - '3000'
    command: 'npm start'
